main: net.tfminecraft.research.Research
api-version: '1.21.10'
name: Research
version: '${project.version}'
author: Drefvelin
depend: [MMOItems, MythicLib, ItemsAdder, TLibs, RPCharacters]
softdepend: [MMOCore]

commands:
  research:
    description: Research admin commands
    usage: /research reload
    permission: research.admin

permissions:
  research.admin:
    description: Allows Research reload and admin commands
    default: op
